### ISSUE TITLE
map distortion

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#664] opened 2015-07-06 10:00 UTC
when using the getfeatureinfo, the map is now distorted

**Comment by jaykayone** [comment] 2015-07-07 06:46
this is a regression

**Comment by jaykayone** [comment] 2015-07-07 12:42
as @pgiraud is not there today, can you have a look please @elemoine?

**Comment by elemoine** [comment] 2015-07-07 15:59
I did not have time for that. I just noticed that the problem is related to https://github.com/camptocamp/ngeo/pull/256. In the case of the "info panel" the animation callback is called with a target element which is not the one onto which the resizemap directive is attached.

**Comment by jaykayone** [comment] 2015-07-08 06:46
@elemoine do you have the time to work on this today? 
If not, do you think, we can fix it on the application side, or does this have to be tackled in ngeo?

It's the last issue preventing us to make user tests.

Thanks
Jeff

**Comment by pgiraud** [comment] 2015-07-08 11:46
I'm back to work. I'll dig into this this afternoon.

**Comment by jaykayone** [comment] 2015-07-08 11:48
thanks

**Comment by pgiraud** [comment] 2015-07-08 12:03
It looks like it happens in other cases. Here's an other one:
 - right click on map -> info panel opens,
 - click on closing cross -> info panel closes and map is distorted.

**Comment by jaykayone** [comment] 2015-07-08 12:10
yes, that's correct

**Comment by rmichaelis** [comment] 2015-07-08 12:16
it seems to happen as soon as the left panel is not opened by one of the 3 left button.
I have the feeling that it happens when the side panel is opened through a binding in a directive.

**Comment by pgiraud** [comment] 2015-07-08 12:47
It looks like something weird happens when there's a ngRepeat or ngShow in child elements.
I made a sample to show this. http://plnkr.co/edit/KEIfoHDiw7n97ljLm2CZ
And sent a message to the mailing list https://groups.google.com/forum/#!topic/angular/T0j0gg1G2P0

**Comment by jaykayone** [comment] 2015-07-08 13:29
Is there an alternative way of repairing this? 
if possible I do not want to wait for angular to fix a bug

**Comment by pgiraud** [comment] 2015-07-08 13:33
I understand. I'm trying to find a workaround.
By the way, here's an example showing how easy it can be reproduced.
https://github.com/camptocamp/ngeo/commit/41a0753c2cb80e97339956fd0781b423f78dc1e1

**Comment by rmichaelis** [comment] 2015-07-08 14:21
Is this issue related to this one #679  ?

**Comment by elemoine** [comment] 2015-07-08 15:54
> Is this issue related to this one #679 ?

Not really. But #697, which fixes this issue, removes `ngAnimate` entirely, which will fix #679!

**Closed** 2015-07-08 16:23 UTC
Labels: bug, ready
