### ISSUE TITLE
mymaps use cases

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#882] opened 2015-10-07 13:10 UTC
@pgiraud I think we didn't discussed about the following use cases :
1) A user has already drawn features on a map.
Then he opens an existing map. What's happen with the previously drawn features ?
- Are they deleted ? 
- Are they automatically saved in the opened mymap ?  (I don't think so)
- Should we have 2 lists ? one for the mymaps elements and the other for the already drawn elements ? That means we should have a way to copy the existing element into the current mymaps

2) A user opened a mymaps coming from an other user.
Then he draws new features on the map.
- As previously said, Should we have 2 lists ?

Do you see what I mean ?

**Comment by pgiraud** [comment] 2015-10-09 07:21
Hi,

I do see what you mean. I think it was discussed but it doesn't appear in the mockups. Or maybe it was only in my mind.
First of all, I'd start with an other use case. What if a user already drew features on the map and then creates a new map. IMO, the drawn features should be automatically added to the new map.
So, for case 1) I do think we can do the same ie. automatically add the features drawn previously to the existing map. An other option, in my opinion would be to ask the user if he wants to keep the previously drawn features, in which case they are added to the map.

For case 2), the intended behaviour was to have one list but with a visual differentiation between the features from the map and the ones drawn by the user. We would rely on the "editable" property to distinguish the different features. This property would be `true` when the features are drawn by the user or from a map owned by him. It would be `false` when the features come from a map he doesn't own. This `editable` property will also help telling how the feature popup will look ie. whether or not to show the edit/delete buttons.

**Comment by rmichaelis** [comment] 2015-10-09 07:49
Thanks @petzlux 

@jaykayone Do you agree ?

**Comment by jaykayone** [comment] 2015-10-09 08:10
I see one problem that I would like to discuss further:

The user drew lines on a map, he than opens one of his own maps where he has editing rights.

I don't want those features to be automagically added to the map without asking him if we wants to.

We could ask him the following:

You have drawn features, do you want to:

x delete them before loading the map?
x add them to the map
x keep them as drawings

....

maybe this is too complicated for the user though?

What do you think?

**Comment by pgiraud** [comment] 2015-10-16 14:29
Indeed we can consider asking the user. I would rather try to keep it as simple as possible.
It should still be possible to add such a feature later.

**Comment by jaykayone** [comment] 2015-10-16 14:45
I don't like asking the user either (yet)

which should be the standard case then?

**Comment by pgiraud** [comment] 2015-10-16 14:54
Automatically add the drawings to the map (as soon as the map belongs to the current user).

This means that there should be 2 kind of features in the list :
 - features not belonging to user (in map from other user),
 - features belonging to user (drawn or from map).

**Comment by jaykayone** [comment] 2015-10-16 15:32
@rmichaelis do you want @pgiraud to help here after your pr gets merged?

**Comment by rmichaelis** [comment] 2015-10-16 15:35
Maybe for the layout.
I'll ask him if I need.

2015-10-16 17:32 GMT+02:00 Jeff Konnen <notifications@github.com>:

**Closed** 2015-11-05 07:22 UTC
Labels: Mymaps
