### ISSUE TITLE
The scale bar is behind the map

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#198] opened 2015-01-28 15:28 UTC
The scale bar is behind the map

**Comment by elemoine** [comment] 2015-02-02 14:32
@rmichaelis could you please more specific? What scale bar are you talking about exactly? The scale line?

**Comment by rmichaelis** [comment] 2015-02-02 15:56
Here is the problem : 
![scale](https://cloud.githubusercontent.com/assets/5594996/6003457/41b93e0c-aafc-11e4-9daf-416f4f4ea6df.PNG)

**Comment by elemoine** [comment] 2015-02-02 16:01
That is VERY VERY strange. What browser? What layer? How can I reproduce that?

**Comment by pgiraud** [comment] 2015-02-02 16:04
Not that strange.
We chose to put the scaleline component outside the map.
Adding the following in the less files should do the job:
```
.ol-scale-line {
  z-index: 2;
}
```

**Comment by pgiraud** [comment] 2015-02-02 16:05
But actually, the scaleline, is supposed to be moved to the info panel (behind the "i" button) eventually.

**Comment by elemoine** [comment] 2015-02-02 16:07
Oh, I thought the scale line was in the map. The scaleline is going to move to the collapsible panel anyway, so no need to try to fix that for now I guess.

**Comment by pgiraud** [comment] 2015-02-04 08:39
I think we can close this issue because it will be addressed with the info panel. Closing.

**Closed** 2015-02-04 08:40 UTC
Labels: Base/Layout, bug
